name: PVS-Studio build analysis

on:
  push:
    branches:
      - main
      - develop

  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build-component:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        idf_ver: [release-v4.4]
        idf_target: [esp32]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        # academic work ${{ secrets.PVS_STUDIO_CREDENTIALS }}
      - name: Install tools
        run: |
          wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt \
            | apt-key add -
          wget -O /etc/apt/sources.list.d/viva64.list \
            https://files.pvs-studio.com/etc/viva64.list
          apt update
          apt install pvs-studio strace
          pvs-studio-analyzer credentials PVS-Studio Free FREE-FREE-FREE-FREE
      - name: Build for ESP32
        env:
          PLATFORM: linux64
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build
      - name: Analyze
        run: |
          pvs-studio-analyzer analyze -f build/compile_commands.json -j
      - name: Convert report
        run: |
          plog-converter -t sarif -o pvs-report.sarif PVS-Studio.log
      - name: Publish report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
